### ISSUE TITLE
Voice: v2: ReadPacket() never finishes when region changes

### ISSUE THREAD

**Issue by 1lann** [diamondburned/arikawa#238]
When the voice server's region changes, `ReadPacket()` will never finish as it (presumably) waits indefinitely to read a packet from the old UDP voice server.

I believe the solution here is to `SetReadDeadline` to something like 1-2 seconds on the underlying connection, read, check if the gateway has changed, otherwise re-attempt the read and loop.

**Comment by diamondburned** [comment]
This seems like it can be a fix on the caller's end, but it seems like the actual issue is quite a bit more work to fix.

For the record, the problem here seems to be that, even with a proper fix, the user would have to handle the UDP connection instance changing, and ideally, we'd want that to be seamless. In order to do this, the UDP connection instance should have a way to reconnect to another UDP server.

**Comment by diamondburned** [comment]
I think `udp.Connection` has to be redesigned into something like a `udp.Dialer` or `udp.ConnectionState`, where it can manage its own UDP connection while also allowing itself to be reconnected to something else. Then, `ReadPacket` can work transparently and wait for `ConnectionState` to be done.

This, of course, is a breaking change, so I will have to do it on the v3 branch.

**Comment by diamondburned** [comment]
Just as a note for myself: `udp.ConnectionState` will have to have its own mutex, but the mutex must not be acquired during reconnection. This is to prevent `ReadPacket` from blocking indefinitely without a way for the context to be cancelled. The issue is figuring out what behavior `ReadPacket` should have if it sees the state is reconnecting, though.
